sonar.projectKey=My-Project_key
sonar.projectName=My-Project
sonar.java.binaries=.
sonar.projectVersion=1.0

# Source code location
sonar.sources=.

# Encoding
#sonar.sourceEncoding=UTF-8

# Optional: exclusions
#sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Optional: test files
# sonar.tests=test
# sonar.test.inclusions=**/*Test*,**/*Spec*

