# env: sit ,  cicd pipeline for vTransact application 

name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          persist_credentials: false
          fetch-depth: 0
       
      - name: Setup Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven in Batch mode
        run: mvn -B package --file pom.xml
